name: Deployment Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install deps
        run: npm install --no-audit --no-fund --no-optional

      - name: Lint
        run: npm run eslint

      - name: Create env file
        run: |
          echo "${{ vars.VITE_API_BASE_URL }}" > .env

      - name: 🔨 Build
        run: npm run build

      - name: 🧪 Test
        run: npm test
